//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace WebApplication1.ControlBodyService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IControlBodyService", Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class ControlBodyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLicensesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendInspectionDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInspectionProcessingStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ControlBodyService() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_ControlBodyService_ControlBodyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLicensesCompletedEventHandler GetLicensesCompleted;
        
        /// <remarks/>
        public event SendInspectionDataCompletedEventHandler SendInspectionDataCompleted;
        
        /// <remarks/>
        public event GetInspectionProcessingStatusCompletedEventHandler GetInspectionProcessingStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FANC/DataExchange/Contracts/ControlBody/v1_00/IControlBodyService/GetLicen" +
            "ses", RequestNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", ResponseNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetLicensesResult GetLicenses([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetLicensesRequest request) {
            object[] results = this.Invoke("GetLicenses", new object[] {
                        request});
            return ((GetLicensesResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetLicensesAsync(GetLicensesRequest request) {
            this.GetLicensesAsync(request, null);
        }
        
        /// <remarks/>
        public void GetLicensesAsync(GetLicensesRequest request, object userState) {
            if ((this.GetLicensesOperationCompleted == null)) {
                this.GetLicensesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLicensesOperationCompleted);
            }
            this.InvokeAsync("GetLicenses", new object[] {
                        request}, this.GetLicensesOperationCompleted, userState);
        }
        
        private void OnGetLicensesOperationCompleted(object arg) {
            if ((this.GetLicensesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLicensesCompleted(this, new GetLicensesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FANC/DataExchange/Contracts/ControlBody/v1_00/IControlBodyService/SendInsp" +
            "ectionData", RequestNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", ResponseNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SendInspectionDataResult SendInspectionData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SendInspectionDataRequest request) {
            object[] results = this.Invoke("SendInspectionData", new object[] {
                        request});
            return ((SendInspectionDataResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendInspectionDataAsync(SendInspectionDataRequest request) {
            this.SendInspectionDataAsync(request, null);
        }
        
        /// <remarks/>
        public void SendInspectionDataAsync(SendInspectionDataRequest request, object userState) {
            if ((this.SendInspectionDataOperationCompleted == null)) {
                this.SendInspectionDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendInspectionDataOperationCompleted);
            }
            this.InvokeAsync("SendInspectionData", new object[] {
                        request}, this.SendInspectionDataOperationCompleted, userState);
        }
        
        private void OnSendInspectionDataOperationCompleted(object arg) {
            if ((this.SendInspectionDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendInspectionDataCompleted(this, new SendInspectionDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FANC/DataExchange/Contracts/ControlBody/v1_00/IControlBodyService/GetInspe" +
            "ctionProcessingStatus", RequestNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", ResponseNamespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetInspectionProcessingStatusResult GetInspectionProcessingStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetInspectionProcessingStatusRequest request) {
            object[] results = this.Invoke("GetInspectionProcessingStatus", new object[] {
                        request});
            return ((GetInspectionProcessingStatusResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetInspectionProcessingStatusAsync(GetInspectionProcessingStatusRequest request) {
            this.GetInspectionProcessingStatusAsync(request, null);
        }
        
        /// <remarks/>
        public void GetInspectionProcessingStatusAsync(GetInspectionProcessingStatusRequest request, object userState) {
            if ((this.GetInspectionProcessingStatusOperationCompleted == null)) {
                this.GetInspectionProcessingStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInspectionProcessingStatusOperationCompleted);
            }
            this.InvokeAsync("GetInspectionProcessingStatus", new object[] {
                        request}, this.GetInspectionProcessingStatusOperationCompleted, userState);
        }
        
        private void OnGetInspectionProcessingStatusOperationCompleted(object arg) {
            if ((this.GetInspectionProcessingStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInspectionProcessingStatusCompleted(this, new GetInspectionProcessingStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class GetLicensesRequest {
        
        private System.DateTime sinceDateField;
        
        private bool sinceDateFieldSpecified;
        
        /// <remarks/>
        public System.DateTime SinceDate {
            get {
                return this.sinceDateField;
            }
            set {
                this.sinceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SinceDateSpecified {
            get {
                return this.sinceDateFieldSpecified;
            }
            set {
                this.sinceDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class GetInspectionProcessingStatusResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class GetInspectionProcessingStatusRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class SendInspectionDataResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class SendInspectionDataRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Organisation {
        
        private Address addressField;
        
        private string fANCNumberField;
        
        private Identifier[] identifiersField;
        
        private string nameField;
        
        private string shortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FANCNumber {
            get {
                return this.fANCNumberField;
            }
            set {
                this.fANCNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Identifier[] Identifiers {
            get {
                return this.identifiersField;
            }
            set {
                this.identifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Address {
        
        private AddressType addressTypeField;
        
        private bool addressTypeFieldSpecified;
        
        private BelgianAddress belgianAddressField;
        
        private ForeignAddress foreignAddressField;
        
        /// <remarks/>
        public AddressType AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressTypeSpecified {
            get {
                return this.addressTypeFieldSpecified;
            }
            set {
                this.addressTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public BelgianAddress BelgianAddress {
            get {
                return this.belgianAddressField;
            }
            set {
                this.belgianAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ForeignAddress ForeignAddress {
            get {
                return this.foreignAddressField;
            }
            set {
                this.foreignAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public enum AddressType {
        
        /// <remarks/>
        BelgianAddress,
        
        /// <remarks/>
        ForeignAddress,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class BelgianAddress {
        
        private string cityField;
        
        private string cityNISCodeField;
        
        private string houseNumberField;
        
        private string postalCodeField;
        
        private string streetField;
        
        private string streetCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CityNISCode {
            get {
                return this.cityNISCodeField;
            }
            set {
                this.cityNISCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class ForeignAddress {
        
        private Country countryField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string line3Field;
        
        private string line4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Country Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Line3 {
            get {
                return this.line3Field;
            }
            set {
                this.line3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Line4 {
            get {
                return this.line4Field;
            }
            set {
                this.line4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Country {
        
        private string fullNameField;
        
        private string iSO_3166_1_Alpha_2_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ISO_3166_1_Alpha_2_Code {
            get {
                return this.iSO_3166_1_Alpha_2_CodeField;
            }
            set {
                this.iSO_3166_1_Alpha_2_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Identifier {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class OrganisationLicensee {
        
        private Organisation establishmentField;
        
        private Organisation licenseHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Organisation Establishment {
            get {
                return this.establishmentField;
            }
            set {
                this.establishmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Organisation LicenseHolder {
            get {
                return this.licenseHolderField;
            }
            set {
                this.licenseHolderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class NaturalPerson {
        
        private Address addressField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string fANCNumberField;
        
        private string firstNameField;
        
        private System.Nullable<Gender> genderField;
        
        private bool genderFieldSpecified;
        
        private Identifier[] identifiersField;
        
        private string lastNameField;
        
        private Country nationalityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FANCNumber {
            get {
                return this.fANCNumberField;
            }
            set {
                this.fANCNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<Gender> Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Identifier[] Identifiers {
            get {
                return this.identifiersField;
            }
            set {
                this.identifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Country Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public enum Gender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class NaturalPersonLicensee {
        
        private NaturalPerson licenseHolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NaturalPerson LicenseHolder {
            get {
                return this.licenseHolderField;
            }
            set {
                this.licenseHolderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Licensee {
        
        private NaturalPersonLicensee naturalPersonLicenseeField;
        
        private OrganisationLicensee organisationLicenseeField;
        
        private LicenseeType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NaturalPersonLicensee NaturalPersonLicensee {
            get {
                return this.naturalPersonLicenseeField;
            }
            set {
                this.naturalPersonLicenseeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrganisationLicensee OrganisationLicensee {
            get {
                return this.organisationLicenseeField;
            }
            set {
                this.organisationLicenseeField = value;
            }
        }
        
        /// <remarks/>
        public LicenseeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public enum LicenseeType {
        
        /// <remarks/>
        Organisation,
        
        /// <remarks/>
        NaturalPerson,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class Unit {
        
        private SIPrefix sIPrefixField;
        
        private bool sIPrefixFieldSpecified;
        
        private string unitSymbolField;
        
        /// <remarks/>
        public SIPrefix SIPrefix {
            get {
                return this.sIPrefixField;
            }
            set {
                this.sIPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIPrefixSpecified {
            get {
                return this.sIPrefixFieldSpecified;
            }
            set {
                this.sIPrefixFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UnitSymbol {
            get {
                return this.unitSymbolField;
            }
            set {
                this.unitSymbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public enum SIPrefix {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        k,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        da,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        c,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        µ,
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        p,
        
        /// <remarks/>
        f,
        
        /// <remarks/>
        a,
        
        /// <remarks/>
        z,
        
        /// <remarks/>
        y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class LicenseItemCharacteristic {
        
        private System.Nullable<decimal> quantityField;
        
        private bool quantityFieldSpecified;
        
        private Unit unitField;
        
        private ReferenceCode unitGroupCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Unit Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode UnitGroupCode {
            get {
                return this.unitGroupCodeField;
            }
            set {
                this.unitGroupCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class ReferenceCode {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class LicenseItem {
        
        private System.Nullable<int> amountField;
        
        private bool amountFieldSpecified;
        
        private ReferenceCode amountTypeCodeField;
        
        private ReferenceCode categoryCodeField;
        
        private LicenseItemCharacteristic[] characteristicsField;
        
        private System.Nullable<bool> isHASSField;
        
        private bool isHASSFieldSpecified;
        
        private string remarkField;
        
        private ReferenceCode typeCodeField;
        
        private ReferenceCode useCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode AmountTypeCode {
            get {
                return this.amountTypeCodeField;
            }
            set {
                this.amountTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode CategoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public LicenseItemCharacteristic[] Characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsHASS {
            get {
                return this.isHASSField;
            }
            set {
                this.isHASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsHASSSpecified {
            get {
                return this.isHASSFieldSpecified;
            }
            set {
                this.isHASSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode UseCode {
            get {
                return this.useCodeField;
            }
            set {
                this.useCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
    public partial class License {
        
        private System.Nullable<bool> commissioningRequiredField;
        
        private bool commissioningRequiredFieldSpecified;
        
        private System.Nullable<System.DateTime> licenseEndDateField;
        
        private bool licenseEndDateFieldSpecified;
        
        private System.Nullable<System.DateTime> licenseIssueDateField;
        
        private bool licenseIssueDateFieldSpecified;
        
        private LicenseItem[] licenseItemsField;
        
        private string licenseNumberField;
        
        private System.Nullable<System.DateTime> licenseRequestDateField;
        
        private bool licenseRequestDateFieldSpecified;
        
        private System.Nullable<System.DateTime> licenseStartDateField;
        
        private bool licenseStartDateFieldSpecified;
        
        private ReferenceCode licenseTypeCodeField;
        
        private Licensee licenseeField;
        
        private string parentLicenseNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> CommissioningRequired {
            get {
                return this.commissioningRequiredField;
            }
            set {
                this.commissioningRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommissioningRequiredSpecified {
            get {
                return this.commissioningRequiredFieldSpecified;
            }
            set {
                this.commissioningRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LicenseEndDate {
            get {
                return this.licenseEndDateField;
            }
            set {
                this.licenseEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenseEndDateSpecified {
            get {
                return this.licenseEndDateFieldSpecified;
            }
            set {
                this.licenseEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LicenseIssueDate {
            get {
                return this.licenseIssueDateField;
            }
            set {
                this.licenseIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenseIssueDateSpecified {
            get {
                return this.licenseIssueDateFieldSpecified;
            }
            set {
                this.licenseIssueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public LicenseItem[] LicenseItems {
            get {
                return this.licenseItemsField;
            }
            set {
                this.licenseItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LicenseRequestDate {
            get {
                return this.licenseRequestDateField;
            }
            set {
                this.licenseRequestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenseRequestDateSpecified {
            get {
                return this.licenseRequestDateFieldSpecified;
            }
            set {
                this.licenseRequestDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LicenseStartDate {
            get {
                return this.licenseStartDateField;
            }
            set {
                this.licenseStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenseStartDateSpecified {
            get {
                return this.licenseStartDateFieldSpecified;
            }
            set {
                this.licenseStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReferenceCode LicenseTypeCode {
            get {
                return this.licenseTypeCodeField;
            }
            set {
                this.licenseTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Licensee Licensee {
            get {
                return this.licenseeField;
            }
            set {
                this.licenseeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentLicenseNumber {
            get {
                return this.parentLicenseNumberField;
            }
            set {
                this.parentLicenseNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FANC/DataExchange/Contracts/ControlBody/v1_00")]
    public partial class GetLicensesResult {
        
        private License[] licensesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://FANC/DataExchange/Contracts/v1_00")]
        public License[] Licenses {
            get {
                return this.licensesField;
            }
            set {
                this.licensesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetLicensesCompletedEventHandler(object sender, GetLicensesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLicensesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLicensesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetLicensesResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetLicensesResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SendInspectionDataCompletedEventHandler(object sender, SendInspectionDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendInspectionDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendInspectionDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendInspectionDataResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendInspectionDataResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetInspectionProcessingStatusCompletedEventHandler(object sender, GetInspectionProcessingStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInspectionProcessingStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInspectionProcessingStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetInspectionProcessingStatusResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetInspectionProcessingStatusResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591